[hrm]
TEST_URL = https://ipss.asset.techgenzi.com
CHROME_DRIVER_LOCATION = D:\Automation\chromedriver-win64\chromedriver.exe
EDGE_DRIVER_LOCATION = D:/edgedriver_win64/msedgedriver.exe
GECKO_DRIVER_LOCATION = D:\geckodriver-v0.33.0-win64\geckodriver.exe
