import time
import unittest

from driver import driver
from selenium.webdriver.common.by import By

from hrm_automation.base import BasePage
from hrm_automation.locators import Locators
class Employee(BasePage,unittest.TestCase):
    """
    Login common module for all user roles.
    """
    def __init__(self, driver):
        super().__init__(driver)
    def emp_tab(self):
        # self.click(Locators.DRAW)
        # time.sleep(2)
        # self.click(Locators.EMP_SIDEBAR_DRAW)
        # time.sleep(5)
        # self.click(Locators.EMP_CARD)
        # time.sleep(3)
        # self.click(Locators.HOME_SIDEBAR)
        # time.sleep(1)
        self.click(Locators.EMP_SIDEBAR)
        time.sleep(5)

        # time.sleep(5)21`
    def search(self):
        self.click(Locators.EMP_SEARCH)
        time.sleep(1)
        self.enter_text(Locators.SEARCH_NAME,"520943447304")
        time.sleep(1)
        self.clear(Locators.SEARCH_NAME)
        time.sleep(1)
        self.enter_text(Locators.SEARCH_NAME,"DHARANI")
        time.sleep(1)
        self.click(Locators.SEARCH_CLOSE)
        time.sleep(1)
        self.clear(Locators.EMP_SEARCH_BT)
        time.sleep(1)
        self.enter_text(Locators.EMP_SEARCH_BT,"DHARANI")
        time.sleep(5)
        self.click(Locators.VIEW)
        time.sleep(2)
        self.click(Locators.PROFILE_DOWNLOAD)
        time.sleep(4)
        self.click(Locators.PRO_EDIT)
        time.sleep(4)
        self.click(Locators.PRO_EMP_GO)
        time.sleep(2)
        self.click(Locators.PRO_GO)
        time.sleep(1)
        # self.click(Locators.EMP_RESET_BT)
        # time.sleep(2)


    def quick(self):
        #check the cancel button
        self.click(Locators.QUICKONBOARD)
        time.sleep(1)
        self.click(Locators.QCANCEL)
        time.sleep(1)
        #Add the quick onboard
        self.click(Locators.QUICKONBOARD)
        time.sleep(1)
        self.enter_text(Locators.QNAME,"SRIMATHI")
        time.sleep(1)
        self.dropdown_click(Locators.QGENDER,1)
        time.sleep(1)
        self.enter_text(Locators.QAADHAR,"570009700349")
        time.sleep(1)
        self.enter_text(Locators.QDOJ,"12-12-2021")
        time.sleep(1)
        self.enter_text(Locators.QUDOJ,"14-12-2021")
        time.sleep(1)
        self.dropdown_click(Locators.QSHIFT,1)
        time.sleep(1)
        self.dropdown_click(Locators.QCATEGORY,1)
        time.sleep(1)
        self.dropdown_click(Locators.QDEPT,4)
        time.sleep(1)
        self.dropdown_click(Locators.QDESG,1)
        time.sleep(1)
        self.click(Locators.QSUBMIT)
        time.sleep(5)


        # CHECK WHETHER THE EMPLOYEE IS ADDING OR NOT
    def add(self):
        self.click(Locators.DETAIL_ONBOARD)
        time.sleep(1)
        # CLICK THE GO BACK BUTTON
        self.click(Locators.EMP_GO_BACK)
        time.sleep(1)
        #CLICK THE ADD BUTTON AND CLICK THE SUBMIT BUTTON
        self.click(Locators.DETAIL_ONBOARD)
        time.sleep(1)
        self.click(Locators.NEXT)
        time.sleep(5)
        photo_path = "D:/HRM-Backend/hrm_automation/hrm_test_cases/photo.jpg"  # Replace with the actual file path
        self.file_upload(Locators.FILE_UPLOAD, photo_path)
        time.sleep(1)
        self.enter_text(Locators.FNAME,"MEGA")
        time.sleep(1)
        self.enter_text(Locators.MNAME,"")
        time.sleep(1)
        self.enter_text(Locators.LNAME, "Krish")
        time.sleep(1)
        self.enter_text(Locators.DOB,"13-09-2002")
        time.sleep(1)
        self.dropdown_click(Locators.GENDER,1)
        time.sleep(1)
        self.dropdown_click(Locators.RELIGION,1)
        time.sleep(1)
        self.dropdown_click(Locators.NATIONALITY,1)
        time.sleep(1)
        self.dropdown_click(Locators.BLOOD_GRP,1)
        time.sleep(1)
        self.dropdown_click(Locators.DISABLTY,1)
        time.sleep(1)
        self.dropdown_click(Locators.MARITALSTS,1)
        time.sleep(1)
        self.enter_text(Locators.MOB,"8499345678")
        time.sleep(1)
        self.enter_text(Locators.ALT_MOB,"8712995678")
        time.sleep(1)
        self.enter_text(Locators.EMAIL,"jd@gmail.com")
        time.sleep(1)
        self.enter_text(Locators.ALT_EMAIL,"jd1@gmail.com")
        time.sleep(5)
        self.dropdown_click(Locators.CATE,5)
        time.sleep(1)
        self.driver.execute_script("window.scrollBy(0,500)")
        time.sleep(1)
        self.enter_text(Locators.CAD1,"8th cross street")
        time.sleep(1)
        self.enter_text(Locators.CAD2,"srivansion road")
        time.sleep(1)
        self.dropdown_click(Locators.VILLAGE,1)
        time.sleep(1)
        self.enter_text(Locators.PIN,"625003")
        time.sleep(5)
        self.enter_text(Locators.PAD1, "8th cross street")
        time.sleep(1)
        self.enter_text(Locators.PAD2, "srivansion road")
        time.sleep(1)
        self.dropdown_click(Locators.PVILLAGE, 2)
        time.sleep(1)
        self.enter_text(Locators.PPIN, "625003")
        time.sleep(1)
        self.driver.execute_script("window.scrollBy(0,800)")
        time.sleep(1)
        self.click(Locators.CHECK)
        time.sleep(1)
        # self.click(Locators.CHECKBOX)
        # time.sleep(1)
        self.click(Locators.NEXT)
        time.sleep(6)
        self.enter_text(Locators.DOJ,"03-02-2023")
        time.sleep(6)
        self.enter_text(Locators.SAT_DOJ, "15-12-2023")
        time.sleep(5)
        self.enter_text(Locators.UNIT_DOJ, "17-12-2023")
        time.sleep(5)
        self.dropdown_click(Locators.SHIFT, 1)
        time.sleep(1)
        self.dropdown_click(Locators.OVERTIME,1)
        time.sleep(1)
        #id proof
        photo_path = "D:/HRM-Backend/hrm_automation/hrm_test_cases/photo.jpg"
        self.file_upload(Locators.FILE_UPLOAD1, photo_path)
        time.sleep(2)
        self.enter_text(Locators.NAME_ADHAR,"deena")
        time.sleep(1)
        self.enter_text(Locators.AADHAR_N0,"500722888156")
        time.sleep(1)
        self.enter_text(Locators.PAN_NO,"SPEWR1987A")
        time.sleep(4)
        # photo_path = "D:/HRM-Backend/hrm_automation/hrm_test_cases/photo.jpg"
        # self.file_upload(Locators.FILE_UPLOAD2, photo_path)
        # time.sleep(6)
        self.enter_text(Locators.DL_NO,"JG74DWSDRT67808/378/0")
        time.sleep(1)
        self.enter_text(Locators.PASSPORT_N0,"K9177567890982891112")
        time.sleep(1)
        self.enter_text(Locators.PASSPORT_PLACE,"Chennai")
        time.sleep(1)
        self.enter_text(Locators.PASSPORT_ISSUE_DT,"13-09-2017")
        time.sleep(1)
        self.enter_text(Locators.PASSPORT_EXPIRY_DT,"13-09-2023")
        time.sleep(1)
        self.dropdown_click(Locators.DEPT,1)
        time.sleep(1)
        self.dropdown_click(Locators.DESG,1)
        time.sleep(1)
        self.dropdown_click(Locators.GRADE,1)
        time.sleep(1)
        self.click(Locators.NEXT_EMP)
        time.sleep(3)
        #social security
        self.dropdown_click(Locators.SAL_TYPE,1)
        time.sleep(2)
        self.enter_text(Locators.DAILY_WAGES,"12000")
        time.sleep(2)
        self.click(Locators.PAYROLL_BT)
        time.sleep(2)
        # self.dropdown_click(Locators.PAY_TEMP,1)
        # time.sleep(2)
        self.click(Locators.PAY_SAVE)
        time.sleep(2)
        self.driver.execute_script("window.scrollBy(0,500)")
        time.sleep(1)
        # self.click(Locators.PAY_CLOSE)
        # time.sleep(2)
        self.click(Locators.PAY_GO_BACK)
        time.sleep(5)
        self.click(Locators.NEXT)
        time.sleep(6)
        self.click(Locators.NEXT)
        time.sleep(3)
        self.click(Locators.PF_CHECK)
        time.sleep(2)
        self.enter_text(Locators.PF_NO,"MAAMU98747899177474")
        time.sleep(1)
        self.enter_text(Locators.UAN_NO,"684046126768")
        time.sleep(1)
        self.enter_text(Locators.PF_ISSUE_DT,"07-10-2023")
        time.sleep(1)
        self.enter_text(Locators.PF_RELEIVE_DT,"07-10-2024")
        time.sleep(1)
        self.click(Locators.ARBY_CHECK)
        time.sleep(1)
        self.enter_text(Locators.ARBY_END_DT,"07-10-2024")
        time.sleep(1)
        self.click(Locators.ESI_CHECK)
        time.sleep(1)
        self.driver.execute_script("window.scrollBy(0,500)")
        time.sleep(1)
        self.enter_text(Locators.ESI_NO,"68783T41112440")
        time.sleep(1)
        self.enter_text(Locators.ESI_ISSUE_DT,"07-10-2023")
        time.sleep(1)
        self.enter_text(Locators.ESI_RELEIVE_DT,"07-10-2024")
        time.sleep(1)
        #BANK DETAILS
        self.click(Locators.BANK_DET_BT)
        time.sleep(1)
        self.driver.execute_script("window.scrollBy(0,500)")
        time.sleep(1)
        self.enter_text(Locators.IFSC_CODE,"CIUB991541116")
        time.sleep(1)
        self.enter_text(Locators.BANK_NAME,"city union bank")
        time.sleep(1)
        self.enter_text(Locators.ACC_NO,"5112287034356")
        time.sleep(1)
        self.enter_text(Locators.ACC_HOLD_NAME,"Jeevitha")
        time.sleep(1)
        self.enter_text(Locators.BRANCH_NAME,"TVS NAGAR")
        time.sleep(1)
        self.click(Locators.SAVE_BANK)
        time.sleep(1)
        self.click(Locators.NEXT_2)
        time.sleep(1)
        #Family Details
        self.click(Locators.FAM_BT)
        time.sleep(1)
        self.enter_text(Locators.NAME,"Pandiyarajan")
        time.sleep(1)
        self.enter_text(Locators.AGE,"43")
        time.sleep(1)
        self.enter_text(Locators.RELATIONSHIP,"FATHER")
        time.sleep(1)
        self.click(Locators.NOMINEE)
        self.click(Locators.YES)
        time.sleep(1)
        self.enter_text(Locators.FAM_ADHAR_NO,"786001222400")
        time.sleep(1)
        self.click(Locators.SAVE_FAM)
        time.sleep(1)
        self.click(Locators.FAM_BT)
        time.sleep(1)
        self.driver.execute_script("window.scrollBy(0,500)")
        time.sleep(1)
        #Education Details
        self.click(Locators.EDU_BT)
        time.sleep(1)
        self.enter_text(Locators.DEGREE,"BE")
        time.sleep(1)
        self.enter_text(Locators.INSTITUTION,"VCE")
        time.sleep(1)
        self.enter_text(Locators.PERCENT,98)
        time.sleep(1)
        self.enter_text(Locators.YEAR_PASS,"14-09-2002")
        time.sleep(1)
        self.click(Locators.SAVE_EDU)
        time.sleep(1)
        self.click(Locators.EDU_BT)
        time.sleep(1)
        #Experience Details
        self.click(Locators.EXP_BT)
        time.sleep(1)
        self.driver.execute_script("window.scrollBy(0,300)")
        time.sleep(1)
        self.enter_text(Locators.COMP,"EKALAIV TECHNOLOGIES")
        time.sleep(1)
        self.enter_text(Locators.DESG_EXP,"TESTER")
        time.sleep(1)
        self.enter_text(Locators.EXP_MON,"6")
        time.sleep(1)
        self.enter_text(Locators.SALARY,"70000")
        time.sleep(1)
        self.click(Locators.SAVE_EXP)
        time.sleep(1)
        self.click(Locators.EXP_BT)
        time.sleep(1)
        #Training details
        self.click(Locators.TRAIN_BT)
        time.sleep(1)
        self.driver.execute_script("window.scrollBy(0,300)")
        time.sleep(1)
        self.enter_text(Locators.TITLE,"webdeveloper")
        time.sleep(1)
        self.enter_text(Locators.LOCATION,"chennai")
        time.sleep(1)
        self.enter_text(Locators.DURATION,"6")
        time.sleep(1)
        self.enter_text(Locators.DATE,"12-12-2023")
        time.sleep(1)
        self.click(Locators.SAVE_TRAIN)
        time.sleep(1)
        self.click(Locators.TRAIN_BT)
        time.sleep(1)
        #Miscellenious
        self.click(Locators.MIS_BT)
        time.sleep(1)
        self.driver.execute_script("window.scrollBy(0,300)")
        time.sleep(1)
        self.enter_text(Locators.IDENT,"one scar in hand")
        time.sleep(1)
        self.enter_text(Locators.BLOOD_PRE,"120/50hg/mm")
        time.sleep(1)
        self.enter_text(Locators.HEIGHT,"145")
        time.sleep(1)
        self.enter_text(Locators.WEIGHT,"45")
        time.sleep(1)
        self.dropdown_click(Locators.REFERENCE,1)
        time.sleep(1)
        self.click(Locators.SAVE_MIS)
        time.sleep(1)
        self.click(Locators.GENERATE_EMP)
        time.sleep(3)
    def edit(self):
        self.click(Locators.EMP_EDIT_BT)
        time.sleep(2)
        self.clear(Locators.EDIT_FNAME)
        time.sleep(1)
        self.enter_text(Locators.EDIT_FNAME,"sai")
        time.sleep(1)
        self.clear(Locators.EDIT_MNAME)
        time.sleep(1)
        self.enter_text(Locators.EDIT_MNAME,"sri")
        time.sleep(1)
        self.clear(Locators.EDIT_LNAME)
        time.sleep(1)
        self.enter_text(Locators.EDIT_LNAME,"Vevekh")
        time.sleep(1)
        self.enter_text(Locators.EDIT_DOB,"12-12-2001")
        time.sleep(1)
        self.dropdown_click(Locators.EDIT_GENDER,1)
        time.sleep(1)
        self.dropdown_click(Locators.EDIT_RELIGION,1)
        time.sleep(1)
        self.dropdown_click(Locators.EDIT_NATIONALITY,1)
        time.sleep(1)
        self.dropdown_click(Locators.EDIT_BLOOD_GRP,1)
        time.sleep(1)
        self.dropdown_click(Locators.EDIT_DISABLTY,1)
        time.sleep(1)
        self.dropdown_click(Locators.EDIT_MARITALSTS,1)
        time.sleep(1)
        self.clear(Locators.EDIT_MOB)
        time.sleep(1)
        self.enter_text(Locators.EDIT_MOB,"8678566534")
        time.sleep(1)
        self.clear(Locators.EDIT_ALT_MOB)
        time.sleep(1)
        self.enter_text(Locators.EDIT_ALT_MOB,"7889893434")
        time.sleep(1)
        self.clear(Locators.EDIT_EMAIL)
        time.sleep(1)
        self.enter_text(Locators.EDIT_EMAIL,"pjey@gmail.com")
        time.sleep(1)
        self.clear(Locators.EDIT_ALT_EMAIL)
        time.sleep(1)
        self.enter_text(Locators.EDIT_ALT_EMAIL, "pjey@gmail.com")
        time.sleep(1)
        self.dropdown_click(Locators.CATE,5)
        time.sleep(1)
        #Contact Information
        self.clear(Locators.EDIT_CAD1)
        time.sleep(1)
        self.enter_text(Locators.EDIT_CAD1,"18, cross street")
        time.sleep(1)
        self.clear(Locators.EDIT_CAD2)
        time.sleep(1)
        self.enter_text(Locators.EDIT_CAD2,"Kumbaknonam pudur")
        time.sleep(1)
        self.clear(Locators.EDIT_PIN)
        time.sleep(1)
        self.enter_text(Locators.EDIT_PIN,625001)
        time.sleep(1)
        self.click(Locators.EDIT_NEXT)
        time.sleep(4)
        #employment
        self.enter_text(Locators.EDIT_DOJ,"12-09-2023")
        time.sleep(1)
        self.dropdown_click(Locators.EDIT_SHIFT,1)
        time.sleep(1)
        self.dropdown_click(Locators.EDIT_OVERTIME, 1)
        time.sleep(1)
        #IDENTITY PROOF
        self.clear(Locators.EDIT_NAME_ADHAR)
        time.sleep(3)
        self.enter_text(Locators.EDIT_NAME_ADHAR,"JOE")
        time.sleep(3)
        self.clear(Locators.EDIT_AADHAR_N0)
        time.sleep(3)
        self.enter_text(Locators.EDIT_AADHAR_N0,"770020744678")
        time.sleep(3)
        self.clear(Locators.EDIT_PAN_NO)
        time.sleep(3)
        self.enter_text(Locators.EDIT_PAN_NO,"YIYYE1896S")
        time.sleep(3)
        self.clear(Locators.EDIT_DL_NO)
        time.sleep(3)
        self.enter_text(Locators.EDIT_DL_NO,"RJ813/0/1824623/022")
        time.sleep(3)
        self.clear(Locators.EDIT_PASSPORT_N0)
        time.sleep(3)
        self.enter_text(Locators.EDIT_PASSPORT_N0,"U1533776788800")
        time.sleep(3)
        self.clear(Locators.EDIT_PASSPORT_PLACE,)
        time.sleep(3)
        self.enter_text(Locators.EDIT_PASSPORT_PLACE,"NEWYORK")
        time.sleep(3)
        self.clear(Locators.EDIT_PASSPORT_ISSUE_DT, )
        time.sleep(3)
        self.enter_text(Locators.EDIT_PASSPORT_ISSUE_DT,"24-01-2023")
        time.sleep(3)
        self.clear(Locators.EDIT_PASSPORT_EXPIRY_DT, )
        time.sleep(3)
        self.enter_text(Locators.EDIT_PASSPORT_EXPIRY_DT,"15-12-2023")
        time.sleep(3)
        #Edit the Employee Role
        self.dropdown_click(Locators.DEPT,1)
        time.sleep(3)
        self.dropdown_click(Locators.DESG,1)
        time.sleep(3)
        self.dropdown_click(Locators.GRADE,1)
        time.sleep(3)
        self.click(Locators.NEXT_EMP)
        time.sleep(4)
        #Social Security
        self.clear(Locators.PF_NO)
        time.sleep(1)
        self.enter_text(Locators.PF_NO,"MA6867O5597001MUM234")
        time.sleep(3)
        self.clear(Locators.UAN_NO)
        time.sleep(3)
        self.enter_text(Locators.UAN_NO,"63999900778")
        time.sleep(3)
        self.enter_text(Locators.PF_ISSUE_DT,"04-10-2023")
        time.sleep(2)
        self.enter_text(Locators.PF_RELEIVE_DT,"09-10-2023")
        time.sleep(2)
        self.enter_text(Locators.ARBY_END_DT, "05-10-2023")
        time.sleep(1)
        self.driver.execute_script("window.scrollBy(0,500)")
        time.sleep(1)
        self.clear(Locators.ESI_NO)
        time.sleep(1)
        self.enter_text(Locators.ESI_NO, "5602888177890")
        time.sleep(1)
        self.enter_text(Locators.ESI_ISSUE_DT, "09-10-2023")
        time.sleep(1)
        self.enter_text(Locators.ESI_RELEIVE_DT, "17-10-2023")
        time.sleep(1)
        self.click(Locators.NEXT_2)
        time.sleep(4)
        #Family Details
        self.click(Locators.EDIT_FAM_BT)
        time.sleep(4)
        self.click(Locators.EDIT_FAM_DET)
        time.sleep(3)
        self.clear(Locators.EDIT_NAME)
        time.sleep(1)
        self.enter_text(Locators.EDIT_NAME, "Pandiselvi")
        time.sleep(1)
        self.clear(Locators.EDIT_AGE)
        time.sleep(1)
        self.enter_text(Locators.EDIT_AGE, "36")
        time.sleep(1)
        self.clear(Locators.EDIT_RELATIONSHIP)
        time.sleep(1)
        self.enter_text(Locators.EDIT_RELATIONSHIP, "Mother")
        time.sleep(1)
        self.click(Locators.NOMINEE)
        self.click(Locators.YES)
        time.sleep(1)
        self.clear(Locators.EDIT_FAM_ADHAR_NO)
        time.sleep(1)
        self.enter_text(Locators.EDIT_FAM_ADHAR_NO, "677200346767")
        time.sleep(1)
        self.click(Locators.EDIT_SAVE_FAM)
        time.sleep(1)
        self.click(Locators.EDIT_FAM_BT)
        time.sleep(1)
        #Education Details
        self.click(Locators.EDU_BT)
        time.sleep(1)
        self.driver.execute_script("window.scrollBy(0,250)")
        time.sleep(1)
        self.click(Locators.EDIT_EDUC_DET)
        time.sleep(1)
        self.clear(Locators.DEGREE)
        time.sleep(1)
        self.enter_text(Locators.DEGREE, "BE")
        time.sleep(1)
        self.clear(Locators.INSTITUTION)
        time.sleep(1)
        self.enter_text(Locators.INSTITUTION, "VCE")
        time.sleep(1)
        self.clear(Locators.PERCENT)
        time.sleep(1)
        self.enter_text(Locators.PERCENT, 98)
        time.sleep(1)
        self.enter_text(Locators.YEAR_PASS, "14-09-2002")
        time.sleep(1)
        self.click(Locators.SAVE_EDU)
        time.sleep(1)
        self.click(Locators.EDU_BT)
        time.sleep(1)
        #Experience Details
        self.click(Locators.EDIT_EXP_BT)
        time.sleep(1)
        self.driver.execute_script("window.scrollBy(0,250)")
        time.sleep(1)
        self.click(Locators.EDIT_EX_DET)
        time.sleep(1)
        self.clear(Locators.COMP)
        time.sleep(1)
        self.enter_text(Locators.COMP,"EKALAIV TECHNOLOGIES")
        time.sleep(1)
        self.clear(Locators.DESG_EXP)
        time.sleep(1)
        self.enter_text(Locators.DESG_EXP,"TESTER")
        time.sleep(1)
        self.clear(Locators.EXP_MON)
        time.sleep(1)
        self.enter_text(Locators.EXP_MON,"6")
        time.sleep(1)
        self.clear(Locators.SALARY)
        time.sleep(1)
        self.enter_text(Locators.SALARY,"70000")
        time.sleep(1)
        self.click(Locators.SAVE_EXP)
        time.sleep(1)
        self.click(Locators.EXP_BT)
        time.sleep(1)
        #Training details
        self.click(Locators.EDIT_TRAIN_BT)
        time.sleep(1)
        self.clear(Locators.EDIT_TITLE)
        time.sleep(1)
        self.enter_text(Locators.EDIT_TITLE, " Python webdeveloper")
        time.sleep(1)
        self.clear(Locators.EDIT_LOCATION)
        time.sleep(1)
        self.enter_text(Locators.EDIT_LOCATION, "Chennai")
        time.sleep(1)
        self.clear(Locators.EDIT_DURATION)
        time.sleep(1)
        self.enter_text(Locators.EDIT_DURATION, "9")
        time.sleep(1)
        self.enter_text(Locators.EDIT_DATE, "12-12-2023")
        time.sleep(1)
        self.click(Locators.EDIT_SAVE_TRAIN)
        time.sleep(1)
        self.click(Locators.EDIT_TRAIN_BT)
        time.sleep(1)

        #Miscellaneous
        self.click(Locators.EDIT_MIS_BT)
        time.sleep(1)
        self.driver.execute_script("window.scrollBy(0,500)")
        time.sleep(1)
        self.clear(Locators.EDIT_IDENT)
        time.sleep(1)
        self.enter_text(Locators.EDIT_IDENT,"ONE SCAR IN HAND")
        time.sleep(1)
        self.clear(Locators.EDIT_BLOOD_PRE)
        time.sleep(1)
        self.enter_text(Locators.EDIT_BLOOD_PRE,"180/60 HG MM")
        time.sleep(1)
        self.clear(Locators.EDIT_HEIGHT)
        time.sleep(1)
        self.enter_text(Locators.EDIT_HEIGHT,"156")
        time.sleep(1)
        self.enter_text(Locators.EDIT_WEIGHT,"50")
        time.sleep(1)
        self.dropdown_click(Locators.EDIT_REFERENCE,2)
        time.sleep(1)
        self.click(Locators.EDIT_SAVE_MIS)
        time.sleep(1)
        #Generate Employee
        self.click(Locators.GENERATE_EMP)
        time.sleep(5)
        #DOWNLOAD CSV
    def download(self):
        time.sleep(5)
        self.click(Locators.DOWNLOAD_CSV)
        time.sleep(2)

    def emp_confg(self):
        self.emp_tab()
        # self.search()
        self.quick()
        self.add()
        self.edit()
        self.download()

























