# from lib2to3.pgen2 import driver
#
# from selenium.webdriver import ActionChains
# from selenium.webdriver.common.keys import Keys
# from selenium import webdriver
# from selenium.webdriver.common.by import By
# from selenium.webdriver.common.action_chains import ActionChains
# from selenium.webdriver.common.keys import Keys
# from selenium.webdriver.support.ui import WebDriverWait
# from selenium.webdriver.support import expected_conditions as EC
# import time
# import unittest
# from hrm_automation.base import BasePage
# from hrm_automation.locators import Locators
# class Random_Test(BasePage,unittest.TestCase):
#     """shirt
#     Login common module for all user roles.
#     """
#     def __init__(self, driver):
#         super().__init__(driver)
#
#
#     def randomtest(self):
#         time.sleep(5)
#         self.click(Locators.CONFIG_CARD)
#         time.sleep(5)
#         self.click(Locators.BAND_BTN)
#         time.sleep(1)
#         self.enter_text(Locators.BAND_NAME, "MANAGERMENT STAFF")
#         time.sleep(1)
#         self.clear(Locators.BAND_NAME)
#         time.sleep(1)
#         self.click(Locators.BAND_SAVE)
#         time.sleep(1)
#         self.click(Locators.BAND_BTN)
#         time.sleep(1)
#         self.click(Locators.DESG_BTN)
#         time.sleep(1)
#         self.dropdown_click(Locators.DESG_DEPT, 1)
#         time.sleep(1)
#         self.enter_text(Locators.DESG_DESG, "Accounts manager")
#         time.sleep(1)
#         self.enter_text(Locators.DESG_DESP, "desg description")
#         time.sleep(1)
#         self.click(Locators.DESG_SAVE)
#         time.sleep(1)
#         self.click(Locators.DESG_BTN)
#         time.sleep(1)
#         #Village
#         self.click(Locators.EMP_VILLAGE_BTN)
#         time.sleep(1)
#         self.driver.execute_script("window.scrollBy(0, 500)")
#         time.sleep(2)
#         self.enter_text(Locators.EMP_VILLAGE, "gandhipram")
#         time.sleep(1)
#         self.click(Locators.EMP_VILLAGE_SAVE)
#         time.sleep(2)
#         #shift
#         self.click(Locators.HOME_SIDEBAR)
#         time.sleep(1)
#         self.click(Locators.SHIFT_CARD)
#         time.sleep(1)
#         #ADD THE SHIFT
#         self.click(Locators.SHIFT_ADD)
#         time.sleep(1)
#         self.enter_text(Locators.SHIFT_NAME, "shifwt k12")
#         time.sleep(1)
#         self.click(Locators.SHIFT_DEFAULT)
#         time.sleep(1)
#         self.enter_text(Locators.SHIFT_START, "07:00:00")
#         time.sleep(1)
#         self.enter_text(Locators.SHIFT_END, "03:00:00")
#         time.sleep(1)
#         self.enter_text(Locators.SHIFT_GRACE, "5")
#         time.sleep(1)
#         self.click(Locators.SHIFT_SUBMIT)
#         time.sleep(3)
#
#         #Add Overtime
#         self.click(Locators.HOME_SIDEBAR)
#         time.sleep(1)
#         self.click(Locators.ATT_CONFG_CARD)
#         time.sleep(2)
#         self.click(Locators.OVERTIME_ADD)
#         time.sleep(1)
#         self.enter_text(Locators.OVERTIME_NAME, "oveime121")
#         time.sleep(1)
#         self.enter_text(Locators.OVERTIME_HOURS, "2")
#         time.sleep(1)
#         self.click(Locators.OVERTIME_SUBMIT)
#         time.sleep(5)
#         #Add Permission
#         self.click(Locators.PERMIS_RADIO)
#         time.sleep(2)
#         self.click(Locators.PERMISSION_ADD)
#         time.sleep(1)
#         self.enter_text(Locators.PERMISSION_NAME, "Permi8084589346")
#         time.sleep(1)
#         self.enter_text(Locators.PERMISSION_HOURS, "3")
#         time.sleep(1)
#         self.click(Locators.PERMISSION_SUBMIT)
#         time.sleep(5)
#         #Add Sequence
#         self.click(Locators.HOME_SIDEBAR)
#         time.sleep(1)
#         self.click(Locators.SEQ_CARD)
#         time.sleep(2)
#         table_container = self.driver.find_element(By.CSS_SELECTOR, ".ag-body-horizontal-scroll-viewport")
#         actions = ActionChains(self.driver)
#         scroll_amount = 600  # Adjust this value based on your specific requirement
#         actions.click_and_hold(table_container).move_by_offset(scroll_amount, 0).release().perform()
#         num_scrolls = 5
#         time.sleep(1)
#         self.click(Locators.SEQUENCE_EDIT)
#         time.sleep(1)
#         self.clear(Locators.SEQUENCE_PREFIX)
#         time.sleep(1)
#         self.enter_text(Locators.SEQUENCE_PREFIX,"TGrtyuiyLAna")
#         time.sleep(1)
#         self.clear(Locators.SEQUENCE_DESCRIPTION)
#         self.enter_text(Locators.SEQUENCE_DESCRIPTION,"DESCJRtION")
#         time.sleep(1)
#         self.clear(Locators.SEQUENE_NO_DIGIT)
#         time.sleep(1)
#         self.enter_text(Locators.SEQUENE_NO_DIGIT,"4")
#         time.sleep(1)
#         self.clear(Locators.SEQUENCE_LAST_DIGIT)
#         self.enter_text(Locators.SEQUENCE_LAST_DIGIT,"4")
#         time.sleep(1)
#         self.click(Locators.SEQUENCE_SUBMIT)
#         time.sleep(5)
#         #Assign
#         self.click(Locators.ASSIGN_SIDEBAR)
#         time.sleep(2)
#         self.dropdown_click(Locators.FIL_DEPT, 3)
#         time.sleep(1)
#         self.dropdown_click(Locators.ASS_TYPE, 2)
#         time.sleep(1)
#         self.dropdown_click(Locators.ASS_VALUE, 1)
#         time.sleep(1)
#         self.click(Locators.FIL_ASSIGN1)
#         time.sleep(1)
#         self.click(Locators.ASS_BT)
#         time.sleep(2)
#         self.driver.execute_script("window.scrollBy(0, 500)")
#         time.sleep(2)
#         self.click(Locators.FIL_SUBMIT)
#         time.sleep(1)
#         #EMPLOYEE PAGE
#         self.click(Locators.EMP_SIDEBAR)
#         time.sleep(5)
#         #DOWNLOAD CSV FOR EMPLOYEE
#         self.click(Locators.DOWNLOAD_CSV)
#         time.sleep(2)
#         #DETAIL ONBOARD
#         self.click(Locators.DETAIL_ONBOARD)
#         time.sleep(1)
#         self.enter_text(Locators.FNAME, "KARTHIPKKRaj")
#         time.sleep(1)
#         self.enter_text(Locators.DOB, "13-09-2002")
#         time.sleep(1)
#         self.dropdown_click(Locators.GENDER, 1)
#         time.sleep(1)
#         self.dropdown_click(Locators.NATIONALITY, 1)
#         time.sleep(1)
#         self.dropdown_click(Locators.BLOOD_GRP, 1)
#         time.sleep(1)
#         self.dropdown_click(Locators.CATE, 5)
#         time.sleep(1)
#         self.click(Locators.NEXT)
#         time.sleep(5)
#         self.enter_text(Locators.DOJ, "13-12-2023")
#         time.sleep(5)
#         self.dropdown_click(Locators.SHIFT, 2)
#         time.sleep(1)
#         self.dropdown_click(Locators.OVERTIME, 1)
#         time.sleep(1)
#         self.enter_text(Locators.AADHAR_N0, "956773257895")
#         time.sleep(1)
#         self.driver.execute_script("window.scrollBy(0, 500)")
#         time.sleep(2)
#         self.dropdown_click(Locators.DEPT, 1)
#         time.sleep(1)
#         self.dropdown_click(Locators.DESG, 1)
#         time.sleep(1)
#         self.click(Locators.NEXT_EMP)
#         time.sleep(1)
#         self.dropdown_click(Locators.SAL_TYPE, 1)
#         time.sleep(2)
#         self.enter_text(Locators.DAILY_WAGES, "12000")
#         time.sleep(2)
#         self.click(Locators.PAYROLL_BT)
#         time.sleep(2)
#         self.click(Locators.PAY_SAVE)
#         time.sleep(2)
#         self.driver.execute_script("window.scrollBy(0,500)")
#         time.sleep(1)
#         self.click(Locators.PAY_GO_BACK)
#         time.sleep(5)
#         self.click(Locators.NEXT)
#         time.sleep(6)
#         self.click(Locators.NEXT)
#         time.sleep(3)
#         self.click(Locators.NEXT_2)
#         time.sleep(1)
#         self.click(Locators.EDU_BT)
#         time.sleep(1)
#         self.enter_text(Locators.DEGREE, "BE")
#         time.sleep(1)
#         self.enter_text(Locators.INSTITUTION, "VCE")
#         time.sleep(1)
#         self.enter_text(Locators.PERCENT, 98)
#         time.sleep(1)
#         self.enter_text(Locators.YEAR_PASS, "14-09-2002")
#         time.sleep(1)
#         self.click(Locators.SAVE_EDU)
#         time.sleep(1)
#         self.click(Locators.EDU_BT)
#         time.sleep(1)
#         self.click(Locators.GENERATE_EMP)
#         time.sleep(3)