import time

from Utilities.base import Basepage
from Utilities.locators import Locators


class Document_creation(Basepage):

    def __init__(self, driver):
        super().__init__(driver)

    def document_creation_page(self):
        self.click(Locators.MENU)
        time.sleep(2)
        self.click(Locators.CONFIGURE)
        time.sleep(2)
        self.click(Locators.DOCUMENT_CREATION)
        time.sleep(2)
        # self.click(Locators.DOCUMENT_ADD)
        # time.sleep(2)
        # self.enter_text(Locators.DOCUMENT_NAME, "License")
        # time.sleep(2)
        # self.enter_text(Locators.DOCUMENT_DESC, "License Desc")
        # time.sleep(2)
        # self.enter_text(Locators.DOCUMENT_LABEL1, "Compliance NO")
        # time.sleep(2)
        # self.click(Locators.DOCUMENT_QUES_TYPE)
        # time.sleep(2)
        # self.dropdown_click(Locators.DOCUMENT_QUES_TYPE_LIST, 1, "Text")
        # time.sleep(2)
        # self.click(Locators.DOCUMENT_QUES_VALID_TYPE)
        # time.sleep(2)
        # self.static_dropdown(Locators.DOCUMENT_QUES_VALID_TYPE_LIST, "Special Text")
        # time.sleep(2)
        # self.click(Locators.DOCUMENT_ANS_VALID_TYPE)
        # time.sleep(2)
        # self.dropdown_click(Locators.DOCUMENT_ANS_VALID_TYPE_LIST, 1, "Numeric Only")
        # time.sleep(2)
        #
        # self.click(Locators.DOCUMENT_ADD_LABEL)
        # time.sleep(2)
        # self.scroll_down(500)
        # time.sleep(2)
        # self.enter_text(Locators.DOCUMENT_LABEL2, "ISO Certificate")
        # time.sleep(2)
        # self.click(Locators.DOCUMENT_QUES_TYPE2)
        # time.sleep(2)
        # self.static_dropdown(Locators.DOCUMENT_QUES_TYPE_LIST, "Advanced Dropdown")
        # time.sleep(2)
        # self.click(Locators.DOCUMENT_DATA_TABLE)
        # time.sleep(2)
        # self.dropdown_click(Locators.DOCUMENT_DATA_TABLE, 1, "Externals Data")
        # time.sleep(2)
        #
        # self.click(Locators.DOCUMENT_DATA_COLUMN)
        # time.sleep(2)
        # self.dropdown_click(Locators.DOCUMENT_DATA_COLUMN, 1, "Rule Name")
        # time.sleep(2)
        #
        # self.click(Locators.DOCUMENT_ADD_LABEL)
        # time.sleep(2)
        # self.scroll_down(500)
        # time.sleep(2)
        # self.enter_text(Locators.DOCUMENT_LABEL3, "Compliance Certificate")
        # time.sleep(2)
        # self.click(Locators.DOCUMENT_QUES_TYPE3)
        # time.sleep(2)
        # self.static_dropdown(Locators.DOCUMENT_QUES_TYPE_LIST, "File Upload")
        # time.sleep(2)
        # self.click(Locators.DOCUMENT_PDF)
        # time.sleep(2)
        # self.click(Locators.DOCUMENT_CSV)
        # time.sleep(2)
        # self.click(Locators.DOCUMENT_DOCX)
        # time.sleep(2)
        # self.click(Locators.DOCUMENT_SUBMIT)
        # time.sleep(2)

        self.click (Locators.DOCUMENT_CLICK)
        time.sleep(2)
        self.click(Locators.DOCUMENT_EDIT)
        time.sleep(2)
        self.scroll_down(800)
        time.sleep(2)
        self.click(Locators.DOCUMENT_ADD_LABEL)
        time.sleep(2)
        self.scroll_down(500)
        time.sleep(2)
        self.send_keys(Locators.DOCUMENT_LABEL4,"Training Certificates Exp")
        time.sleep(2)
        self.click(Locators.DOCUMENT_QUES_TYPE4)
        time.sleep(2)
        self.static_dropdown(Locators.DOCUMENT_QUES_TYPE_LIST,"Date")
        time.sleep(2)
        self.click(Locators.DOCUMENT_EXP_DATE)
        time.sleep(2)
        self.click(Locators.DOCUMENT_SUBMIT)
        time.sleep(2)
