import time
import unittest
from hrm_automation.base import BasePage
from hrm_automation.locators import Locators
import logging

from logger import logger

from hrm_automation.logger_file import get_logger

# # Configure logger
logger = logging.getLogger('hrm_logger')
logger.setLevel(logging.DEBUG)  # or INFO, WARNING, ERROR, etc.

# Create file handler
file_handler = logging.FileHandler('hrm_log.log')
file_handler.setLevel(logging.DEBUG)  # or INFO, WARNING, ERROR, etc.

# Create formatter and add it to the handler
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
file_handler.setFormatter(formatter)

# Add handler to the logger
logger.addHandler(file_handler)


class assign(BasePage, unittest.TestCase):
    """
    Login common module for all user roles.
    """

    def __init__(self, driver):
        super().__init__(driver)
        self.logger = get_logger("Assign Page")

    def assign_tab(self):
        time.sleep(2)
        self.click(Locators.HOME_SIDEBAR)
        time.sleep(2)
        self.driver.execute_script("window.scrollBy(0,800)")
        time.sleep(1)
        self.click(Locators.ASSIGN_CARD)
        time.sleep(10)
    # # Filter the department and assign the permission
    #     self.dropdown_click(Locators.FIL_DEPT,5)
    #     time.sleep(1)
    #     self.click(Locators.ASS_RESET)
    #     time.sleep(1)
    #     self.dropdown_click(Locators.ASS_TYPE,9)
    #     time.sleep(1)
    #     self.dropdown_click(Locators.ASS_VALUE,1)
    #     time.sleep(1)
    #     self.click(Locators.FIL_ASSIGN1)
    #     time.sleep(1)
    #     self.click(Locators.FIL_ASSIGN2)
    #     time.sleep(1)
    #     self.click(Locators.FIL_ASSIGN3)
    #     time.sleep(1)
    #     self.click(Locators.ASS_BT)
    #     time.sleep(2)
    #     self.driver.execute_script("window.scrollBy(0, 500)")
    #     time.sleep(2)
    #     # self.click(Locators.FIL_DEASSIGN1)
    #     # time.sleep(1)
    #     # self.click(Locators.FIL_DESASSIG_BT)
    #     # time.sleep(1)
    #     self.click(Locators.FIL_SUBMIT)
    #     time.sleep(1)
        # Filter the Shift and Assign the Shift

        self.driver.execute_script("window.scrollBy(0, -500)")
        time.sleep(2)
        self.click(Locators.ASS_RESET)
        time.sleep(4)
        self.driver.execute_script("window.scrollBy(0, -500)")
        time.sleep(2)
        self.dropdown_click(Locators.ASS_TYPE, 4)
        time.sleep(1)
        self.dropdown_click(Locators.ASS_VALUE, 1)
        time.sleep(1)
        self.enter_text(Locators.ASS_SHIFT_START,"04-04-2025")
        time.sleep(1)
        self.enter_text(Locators.ASS_SHIFT_END,"04-04-2026")
        time.sleep(1)
        self.click(Locators.FIL_ASSIGN1)
        time.sleep(1)
        self.click(Locators.FIL_ASSIGN2)
        time.sleep(1)
        self.click(Locators.FIL_ASSIGN3)
        time.sleep(1)
        self.driver.execute_script("window.scrollBy(0, 500)")
        time.sleep(2)
        self.click(Locators.ASS_BT)
        time.sleep(1)                 
        # self.click(Locators.FIL_DEASSIGN1)
        # time.sleep(1)
        # self.click(Locators.FIL_DESASSIG_BT)
        # time.sleep(1)

        self.click(Locators.FIL_SUBMIT)
        time.sleep(1)
        self.logger.info("Shift is Assigned Sucessfully")



        # self.dropdown_click(Locators.FIL_SHIFT, 1)
        # time.sleep(1)
    # #FILTER THE CATEGORY AND ASSIGN THE OVERTIME
    #     # self.click(Locators.DEPT_DELETE_AS)
    #     # time.sleep(1)
    #     # self.dropdown_click(Locators.FIL_CAT, 30)
    #     # time.sleep(1)
    #     self.driver.execute_script("window.scrollBy(0, -500)")
    #     time.sleep(2)
    #     self.click(Locators.ASS_RESET)
    #     time.sleep(1)
    #     self.driver.execute_script("window.scrollBy(0, -500)")
    #     time.sleep(2)
    #     self.dropdown_click(Locators.ASS_TYPE, 10)
    #     time.sleep(1)
    #     self.dropdown_click(Locators.ASS_VALUE, 1)
    #     time.sleep(1)
    #     self.click(Locators.FIL_ASSIGN1)
    #     time.sleep(1)
    #     self.click(Locators.FIL_ASSIGN2)
    #     time.sleep(1)
    #     # self.click(Locators.FIL_ASSIGN3)
    #     # time.sleep(1)
    #     self.click(Locators.ASS_BT)
    #     time.sleep(1)
    #     # self.click(Locators.FIL_DEASSIGN1)
    #     # time.sleep(1)
    #     # self.click(Locators.FIL_DESASSIG_BT)
    #     # time.sleep(1)
    #     self.driver.execute_script("window.scrollBy(0, 500)")
    #     time.sleep(2)
    #     self.click(Locators.FIL_SUBMIT)
    #     time.sleep(1)

    #Filter the Overtime and assign the overtime
        # self.dropdown_click(Locators.FIL_OT, 1)
        # time.sleep(1)
        # self.driver.execute_script("window.scrollBy(0, -500)")
        # time.sleep(2)
        # self.click(Locators.ASS_RESET)
        # time.sleep(1)
        # self.driver.execute_script("window.scrollBy(0, -500)")
        # time.sleep(2)
        # self.dropdown_click(Locators.ASS_TYPE, 10)
        # time.sleep(1)
        # self.dropdown_click(Locators.ASS_VALUE, 1)
        # time.sleep(1)
        # self.click(Locators.FIL_ASSIGN1)
        # time.sleep(1)
        # self.click(Locators.FIL_ASSIGN2)
        # time.sleep(1)
        # self.click(Locators.FIL_ASSIGN3)
        # time.sleep(1)
        # self.click(Locators.ASS_BT)
        # time.sleep(1)
        # self.click(Locators.FIL_DEASSIGN1)
        # time.sleep(1)
        # self.click(Locators.FIL_DESASSIG_BT)
        # time.sleep(1)
        # self.driver.execute_script("window.scrollBy(0, 500)")
        # time.sleep(2)
        # self.click(Locators.FIL_SUBMIT)
        # time.sleep(1)
    # #Filter the Permission and Assign the Permission
    #     self.dropdown_click(Locators.FIL_PER, 1)
    #     time.sleep(1)
    #     self.click(Locators.ASS_RESET)
    #     time.sleep(1)
    #     self.driver.execute_script("window.scrollBy(0, -500)")
    #     time.sleep(2)
    #     self.dropdown_click(Locators.ASS_TYPE, 9)
    #     time.sleep(1)
    #     self.dropdown_click(Locators.ASS_VALUE, 3)
    #     time.sleep(1)
    #     self.click(Locators.FIL_ASSIGN1)
    #     time.sleep(1)
    #     self.click(Locators.FIL_ASSIGN2)
    #     time.sleep(1)
    #     self.click(Locators.FIL_ASSIGN3)
    #     time.sleep(1)
    #     self.click(Locators.ASS_BT)
    #     time.sleep(1)
    #     self.click(Locators.FIL_DEASSIGN1)
    #     time.sleep(1)
    #     self.click(Locators.FIL_DESASSIG_BT)
    #     time.sleep(1)
    #     self.driver.execute_script("window.scrollBy(0, 500)")
    #     time.sleep(2)
    #     self.click(Locators.FIL_SUBMIT)
    #     time.sleep(1)
    #Assign the Weekoff Which has been allready configured
        self.driver.execute_script("window.scrollBy(0, -500)")
        time.sleep(2)
        self.click(Locators.ASS_RESET)
        time.sleep(1)
        self.dropdown_click(Locators.ASS_TYPE, 3)
        time.sleep(1)
        self.dropdown_click(Locators.ASS_VALUE, 1)
        time.sleep(1)
        self.dropdown_click(Locators.WEEKOFFS_ASSIGN,1)
        time.sleep(1)
        self.click(Locators.FIL_ASSIGN1)
        time.sleep(1)
        self.click(Locators.FIL_ASSIGN2)
        time.sleep(1)
        self.click(Locators.FIL_ASSIGN3)
        time.sleep(1)
        self.click(Locators.ASS_BT)
        time.sleep(1)
        self.driver.execute_script("window.scrollBy(0, 500)")
        time.sleep(2)
        self.click(Locators.FIL_SUBMIT)
        time.sleep(1)
        self.logger.info("Weekoff is Assigned Sucessfully")
        # Assign the Weekoff by giving only few dates
        self.driver.execute_script("window.scrollBy(0, -500)")
        time.sleep(2)
        self.click(Locators.ASS_RESET)
        time.sleep(1)
        self.dropdown_click(Locators.ASS_TYPE, 3)
        time.sleep(1)
        self.dropdown_click(Locators.ASS_VALUE, 2)
        time.sleep(1)
        self.enter_text(Locators.WEEKOFF_ASS_DATE,"14-02-2026")
        time.sleep(1)
        self.click(Locators.WEEKOFF_ASS_ADD_BT)
        time.sleep(1)
        self.click(Locators.WEEKOFF_ASS_REMOVE)
        time.sleep(7)
        self.click(Locators.FIL_ASSIGN1)
        time.sleep(1)
        self.click(Locators.FIL_ASSIGN2)
        time.sleep(1)
        self.click(Locators.FIL_ASSIGN3)
        time.sleep(1)
        self.click(Locators.ASS_BT)
        time.sleep(1)

        self.driver.execute_script("window.scrollBy(0, 500)")
        time.sleep(2)
        self.click(Locators.FIL_SUBMIT)
        time.sleep(5)
        self.logger.info("Selective Date Weekoff is Assigned Sucessfully")
        # Cut the weekoff and replace the weekoff date
        self.driver.execute_script("window.scrollBy(0, -500)")
        time.sleep(2)
        self.click(Locators.ASS_RESET)
        time.sleep(1)
        self.dropdown_click(Locators.ASS_TYPE, 3)
        time.sleep(1)
        self.dropdown_click(Locators.ASS_VALUE, 3)
        time.sleep(1)
        self.enter_text(Locators.ASS_WEEKOFF_CUTDATE,"14-02-2026")
        time.sleep(1)
        self.enter_text(Locators.ASS_WEEKOFF_REPLACEDATE, "14-04-2027")
        time.sleep(1)
        self.click(Locators.FIL_ASSIGN1)
        time.sleep(1)
        self.click(Locators.FIL_ASSIGN2)
        time.sleep(1)
        self.click(Locators.FIL_ASSIGN3)
        time.sleep(1)
        self.click(Locators.ASS_BT)
        time.sleep(1)
        self.driver.execute_script("window.scrollBy(0, 500)")
        time.sleep(2)
        self.click(Locators.FIL_SUBMIT)
        time.sleep(1)
        self.logger.info("Weekoff has been Sucessfully")

    #Assign the holiday

        self.dropdown_click(Locators.ASS_TYPE, 2)
        time.sleep(1)
        self.dropdown_click(Locators.ASS_VALUE, 1)
        time.sleep(4)
        self.click(Locators.FIL_ASSIGN1)
        time.sleep(1)
        self.click(Locators.FIL_ASSIGN2)
        time.sleep(1)
        self.click(Locators.FIL_ASSIGN3)
        time.sleep(1)
        self.click(Locators.ASS_BT)
        time.sleep(1)
        self.driver.execute_script("window.scrollBy(0, 500)")
        time.sleep(2)
        self.click(Locators.FIL_SUBMIT)
        time.sleep(1)
        self.logger.info("Holiday is Assigned Sucessfully")
    #ASSIGN THE LEAVE INITIATE AND DEFAULT LEAVE
        self.driver.execute_script("window.scrollBy(0, -500)")
        time.sleep(2)
        self.click(Locators.ASS_RESET)
        time.sleep(1)
        self.dropdown_click(Locators.ASS_TYPE, 1)
        time.sleep(1)
        self.dropdown_click(Locators.ASS_VALUE, 1)
        time.sleep(1)
        self.enter_text(Locators.ASS_LEAVE_ALLOCATE_DAY, "5")
        time.sleep(1)
        self.dropdown_click(Locators.ASS_LEAVE_TYPE, 1)
        time.sleep(1)
        self.click(Locators.ASS_DEFAULT)
        time.sleep(10)
        self.click(Locators.FIL_ASSIGN1)
        time.sleep(3)
        # self.click(Locators.FIL_ASSIGN2)
        # time.sleep(1)
        # self.click(Locators.FIL_ASSIGN3)
        # time.sleep(1)
        self.click(Locators.ASS_BT)
        time.sleep(1)
        # self.click(Locators.FIL_DEASSIGN1)
        # time.sleep(1)
        # self.click(Locators.FIL_DESASSIG_BT)
        # time.sleep(1)
        self.driver.execute_script("window.scrollBy(0, 500)")
        time.sleep(2)
        self.click(Locators.FIL_SUBMIT)
        time.sleep(1)
        self.logger.info("Default leave is Assigned Sucessfully")
    # ASSIGN THE LEAVE INITIATE LEAVE
        self.driver.execute_script("window.scrollBy(0, -500)")
        time.sleep(2)
        self.click(Locators.ASS_RESET)
        time.sleep(1)
        self.dropdown_click(Locators.ASS_TYPE, 1)
        time.sleep(1)
        self.dropdown_click(Locators.ASS_VALUE, 1)
        time.sleep(1)
        self.enter_text(Locators.ASS_LEAVE_ALLOCATE_DAY, "5")
        time.sleep(1)
        self.dropdown_click(Locators.ASS_LEAVE_TYPE, 1)
        time.sleep(7)
        self.click(Locators.FIL_ASSIGN1)
        time.sleep(1)
        # self.click(Locators.FIL_ASSIGN2)
        # time.sleep(1)
        # self.click(Locators.FIL_ASSIGN3)
        # time.sleep(1)
        self.click(Locators.ASS_BT)
        time.sleep(1)
        self.logger.info("Default with initiate leave is Assigned Sucessfully")
        self.driver.execute_script("window.scrollBy(0, 500)")
        time.sleep(2)
        self.click(Locators.FIL_SUBMIT)
        time.sleep(1)
        self.driver.execute_script("window.scrollBy(0, -500)")
        time.sleep(2)
        self.click(Locators.ASS_RESET)
        time.sleep(1)
        self.dropdown_click(Locators.ASS_TYPE, 1)
        time.sleep(1)
        self.dropdown_click(Locators.ASS_VALUE, 1)
        time.sleep(1)
        self.enter_text(Locators.ASS_LEAVE_ALLOCATE_DAY, "5")
        time.sleep(1)
        self.dropdown_click(Locators.ASS_LEAVE_TYPE, 1)
        time.sleep(15)
        self.click(Locators.FIL_ASSIGN1)
        time.sleep(3)
        # self.click(Locators.FIL_ASSIGN2)
        # time.sleep(1)
        # self.click(Locators.FIL_ASSIGN3)
        # time.sleep(1)
        self.click(Locators.ASS_BT)
        time.sleep(1)
        self.driver.execute_script("window.scrollBy(0, 500)")
        time.sleep(2)
        self.click(Locators.FIL_SUBMIT)
        time.sleep(1)
    # ASSIGN THE EXISTING LEAVE
        self.driver.execute_script("window.scrollBy(0, -500)")
        time.sleep(2)
        self.click(Locators.ASS_RESET)
        time.sleep(1)
        self.dropdown_click(Locators.ASS_TYPE, 1)
        time.sleep(1)
        self.dropdown_click(Locators.ASS_VALUE, 1)
        time.sleep(1)
        self.enter_text(Locators.ASS_LEAVE_ALLOCATE_DAY, "5")
        time.sleep(1)
        self.dropdown_click(Locators.ASS_LEAVE_TYPE, 2)
        time.sleep(10)
        self.click(Locators.FIL_ASSIGN1)
        time.sleep(1)
        self.click(Locators.FIL_ASSIGN2)
        time.sleep(1)
        self.click(Locators.FIL_ASSIGN3)
        time.sleep(5)
        self.click(Locators.ASS_BT)
        time.sleep(1)
        self.driver.execute_script("window.scrollBy(0, 500)")
        time.sleep(2)
        self.click(Locators.FIL_SUBMIT)
        time.sleep(1)
        self.logger.info("Existing leave is Assigned Sucessfully")
        self.driver.execute_script("window.scrollBy(0, -500)")
        time.sleep(2)
        self.click(Locators.ASS_RESET)
        time.sleep(1)
        self.dropdown_click(Locators.ASS_TYPE, 1)
        time.sleep(1)
        self.dropdown_click(Locators.ASS_VALUE, 1)
        time.sleep(1)
        self.dropdown_click(Locators.ASS_LEAVE_TYPE, 1)
        time.sleep(1)
        self.enter_text(Locators.ASS_LEAVE_ALLOCATE_DAY, "5")
        time.sleep(8)
        self.click(Locators.FIL_ASSIGN1)
        time.sleep(1)
        self.click(Locators.FIL_ASSIGN2)
        time.sleep(1)
        self.click(Locators.FIL_ASSIGN3)
        time.sleep(1)
        self.click(Locators.ASS_BT)
        time.sleep(1)
        self.driver.execute_script("window.scrollBy(0, 500)")
        time.sleep(2)
        self.click(Locators.FIL_SUBMIT)
        time.sleep(1)




