import time
import unittest
from hrm_automation.base import BasePage
from hrm_automation.locators import Locators
import logging
from logger import logger

from hrm_automation.logger_file import get_logger

# # Configure logger
logger.setLevel(logging.DEBUG)  # or INFO, WARNING, ERROR, etc.

# Create file handler
file_handler = logging.FileHandler('hrm_log.log')
file_handler.setLevel(logging.DEBUG)  # or INFO, WARNING, ERROR, etc.

# Create formatter and add it to the handler
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
file_handler.setFormatter(formatter)
# Add handler to the logger
logger.addHandler(file_handler)
class attendance(BasePage, unittest.TestCase):
    """
    Login common module for all user roles.
    """

    def __init__(self, driver):
        super().__init__(driver)
        self.logger = get_logger("Attendance")

    def scroll_to_bottom(self):
        # Scroll to the bottom of the page using JavaScript
        self.driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")

    def attendance_tab(self):
        time.sleep(2)
        self.click(Locators.HOME_SIDEBAR)
        time.sleep(2)
        self.driver.execute_script("window.scrollBy(0,300)")
        time.sleep(2)
        self.click(Locators.ATT_CARD)
        time.sleep(8)

    def all(self):
        self.click(Locators.ALL_LIST_TAB)
        time.sleep(6)
        self.click(Locators.ATT_DATE_FILTER)
        time.sleep(2)
        self.click(Locators.ATT_ALL_CUSTOM)
        time.sleep(3)
        self.enter_text(Locators.ATT_ALL_RANGE1, "01-11-2024")
        time.sleep(3)
        self.enter_text(Locators.ATT_ALL_RANGE2, "31-12-2024")
        time.sleep(10)
        self.dropdown_click(Locators.ATT_FIL_EMP, 1)
        time.sleep(10)

        # self.click(Locators.ATT_APPLY_FIL)
        # time.sleep(3)
        self.click(Locators.ATT_ALL_EXCEL)
        time.sleep(2)
        # self.driver.execute_script("window.scrollBy(0,500)")
        # time.sleep(1)
        self.click(Locators.ATT_ALL_RESET)
        time.sleep(5)
        self.click(Locators.ATT_DATE_FILTER)
        time.sleep(2)
        self.click(Locators.ATT_ALL_CUSTOM)
        time.sleep(3)
        self.enter_text(Locators.ATT_ALL_RANGE1, "01-11-2024")
        time.sleep(3)
        self.enter_text(Locators.ATT_ALL_RANGE2, "31-12-2024")
        time.sleep(10)
        self.click(Locators.ATT_ALL_EDIT)
        time.sleep(1)
        self.enter_text(Locators.ATT_ALL_EDIT_PUNCH1, "08:10")
        time.sleep(1)
        self.click(Locators.ATT_NEW_PUNCH_BT)
        time.sleep(1)
        # self.enter_text(Locators.ATT_ALL_NEWDATE, "20-20-2025")
        # time.sleep(1)
        self.enter_text(Locators.ATT_ALL_NEWPUNCH, "09:00")
        time.sleep(1)
        self.click(Locators.ATT_ALL_DELETE)
        time.sleep(1)
        self.click(Locators.ATT_ALL_SAVE)
        time.sleep(3)
        self.logger.info("All list page is working fine in attendance")
        self.click(Locators.ATT_ALL_EDIT_CLOSE)
        time.sleep(3)

    def single_punch(self):
        self.click(Locators.SINGLE_PUNCH_TAB)
        time.sleep(1)
        self.dropdown_click(Locators.ATT_SL_EMP, 1)
        time.sleep(6)
        self.click(Locators.ATT_SL_DATEFIL)
        time.sleep(2)
        self.click(Locators.ATT_SL_MONTH)
        time.sleep(3)
        # self.click(Locators.ATT_SL_APPLY)
        # time.sleep(3)
        self.click(Locators.ATT_SL_EXCEL)
        time.sleep(2)
        # self.driver.execute_script("window.scrollBy(0,500)")
        # time.sleep(1)
        self.click(Locators.ATT_SL_RESET)
        time.sleep(5)
        self.click(Locators.ATT_SL_DATEFIL)
        time.sleep(2)
        self.click(Locators.ATT_SL_MONTH)
        time.sleep(3)
        # self.click(Locators.ATT_SL_APPLY)
        # time.sleep(3)
        self.click(Locators.ATT_SL_EDIT)
        time.sleep(3)
        self.enter_text(Locators.ATT_SL_PUNCH, "08:00")
        time.sleep(1)
        self.click(Locators.ATT_SL_NEWPUNCH_BT)
        time.sleep(1)
        self.scroll_to_bottom()
        time.sleep(1)
        # self.enter_text(Locators.ATT_SL_NEWDATE, "13-12-2024")
        # time.sleep(1)
        self.enter_text(Locators.ATT_SL_NEWPUNCH, "09:00")
        time.sleep(3)
        # self.click(Locators.ATT_SL_DELETE)
        # time.sleep(3)
        self.click(Locators.ATT_SL_SAVE)
        time.sleep(2)
        self.logger.info("Single Punch page is working fine in attendance")
        self.click(Locators.ATT_ALL_EDIT_CLOSE)
        time.sleep(3)

    def outofshift_punch(self):
        self.click(Locators.OUT_OF_SHIFT_TAB)
        time.sleep(3)
        self.dropdown_click(Locators.ATT_OS_EMP, 1)
        time.sleep(6)
        self.click(Locators.ATT_OS_DATE_FIL)
        time.sleep(2)
        self.click(Locators.ATT_OS_MONTH)
        time.sleep(3)

        self.click(Locators.ATT_OS_EXCEL)
        time.sleep(2)

        self.click(Locators.ATT_OS_RESET)
        time.sleep(5)
        # self.click(Locators.ATT_OS_DATE_FIL)
        # time.sleep(2)
        # self.click(Locators.ATT_OS_MONTH)
        # time.sleep(3)
        self.click(Locators.ATT_DATE_FILTER)
        time.sleep(2)
        self.click(Locators.ATT_ALL_CUSTOM)
        time.sleep(3)
        self.enter_text(Locators.ATT_ALL_RANGE1, "01-11-2024")
        time.sleep(3)
        self.enter_text(Locators.ATT_ALL_RANGE2, "30-12-2024")
        time.sleep(10)

        self.click(Locators.ATT_OS_EDIT)
        time.sleep(1)
        self.enter_text(Locators.ATT_OS_PUNCH, "08:00")
        time.sleep(1)
        self.click(Locators.ATT_OS_NEWPUNCH_BT)
        time.sleep(1)
        # self.enter_text(Locators.ATT_OS_NEWDATE, "20-20-2025")
        # time.sleep(1)
        self.enter_text(Locators.ATT_OS_NEWPUNCH, "09:00")
        time.sleep(1)
        # self.click(Locators.ATT_OS_DELETE)
        # time.sleep(1)
        self.click(Locators.ATT_OS_SAVE)
        time.sleep(3)
        self.logger.info("Single Punch page is working fine in attendance")
        self.click(Locators.ATT_ALL_EDIT_CLOSE)
        time.sleep(3)

    def minimum_shift_mins(self):
        self.click(Locators.MIN_SHIFT_MIN_TAB)
        time.sleep(1)
        self.dropdown_click(Locators.ATT_MIN_EMP, 1)
        time.sleep(6)
        self.click(Locators.ATT_MIN_DATEFILTER)
        time.sleep(2)
        self.click(Locators.ATT_MIN_MONTH)
        time.sleep(3)
        # self.click(Locators.ATT_MIN_APPLY)
        # time.sleep(3)
        self.click(Locators.ATT_MIN_EXCEL)
        time.sleep(2)
        # self.driver.execute_script("window.scrollBy(0,500)")
        # time.sleep(1)
        self.click(Locators.ATT_MIN_RESET)
        time.sleep(5)
        self.click(Locators.ATT_DATE_FILTER)
        time.sleep(2)
        self.click(Locators.ATT_ALL_CUSTOM)
        time.sleep(2)
        self.enter_text(Locators.ATT_ALL_RANGE1, "01-10-2024")
        time.sleep(2)
        self.enter_text(Locators.ATT_ALL_RANGE2, "16-12-2024")
        time.sleep(5)
        # self.click(Locators.ATT_MIN_EMP)
        time.sleep(17)
        self.click(Locators.ATT_MIN_EDIT)
        time.sleep(4)
        self.enter_text(Locators.ATT_MIN_PUNCH1, "08:00")
        time.sleep(1)
        self.click(Locators.ATT_MIN_NEWPUNCH)
        time.sleep(1)
        # self.enter_text(Locators.ATT_MIN_PUNCHDATE, "20-20-2025")
        # time.sleep(1)
        self.enter_text(Locators.ATT_MIN_1STPUNCH, "09:00")
        time.sleep(1)
        # self.click(Locators.ATT_MIN_DELETE)
        # time.sleep(1)
        self.click(Locators.ATT_MIN_PUNCH_SAVE)
        time.sleep(1)
        self.logger.info("Minimum Shift Minutes page is working fine in attendance")
        self.click(Locators.ATT_ALL_EDIT_CLOSE)
        time.sleep(3)

    def odd_punch(self):
        self.click(Locators.ODD_PUNCH_TAB)
        time.sleep(1)
        self.dropdown_click(Locators.ATT_ODD_EMP, 1)
        time.sleep(6)
        self.click(Locators.ATT_ODD_DATE_FIL)
        time.sleep(2)
        self.click(Locators.ATT_ODD_MONTH)
        time.sleep(3)
        # self.click(Locators.ATT_ODD_APPLY)
        # time.sleep(3)
        self.click(Locators.ATT_ODD_EXCEL)
        time.sleep(2)
        # self.driver.execute_script("window.scrollBy(0,500)")
        # time.sleep(1)
        self.click(Locators.ATT_ODD_RESET)
        time.sleep(5)
        self.click(Locators.ATT_DATE_FILTER)
        time.sleep(2)
        self.click(Locators.ATT_ALL_CUSTOM)
        time.sleep(3)
        self.enter_text(Locators.ATT_ALL_RANGE1, "01-11-2024")
        time.sleep(3)
        self.enter_text(Locators.ATT_ALL_RANGE2, "31-12-2024")
        time.sleep(20)

        self.click(Locators.ATT_ODD_EDIT)
        time.sleep(4)
        self.enter_text(Locators.ATT_ODD_PUNCH1, "08:00")
        time.sleep(1)
        self.click(Locators.ATT_ODD_NEWPUNCH)
        time.sleep(1)
        # self.enter_text(Locators.ATT_ODD_PUNCH_DATE, "20-20-2025")
        # time.sleep(1)
        self.enter_text(Locators.ATT_ODD_1STPUNCH, "09:00")
        time.sleep(1)
        # self.click(Locators.ATT_ODD_DELETE)
        # time.sleep(1)
        self.click(Locators.ATT_ODD_PUNCH_SAVE)
        time.sleep(1)
        self.logger.info("Odd Punch page is working fine in attendance")
        self.click(Locators.ATT_ALL_EDIT_CLOSE)
        time.sleep(3)

    def bulk_add(self):
        self.click(Locators.BULK_TAB)
        time.sleep(2)
        # self.dropdown_click(Locators.BULK_DEPT_FIL,1)
        # time.sleep(1)
        # self.dropdown_click(Locators.BULK_CAT_FIL, 1)
        # time.sleep(1)
        self.click(Locators.BULK_CHECK1)
        time.sleep(1)
        self.click(Locators.BULK_CHECK2)
        time.sleep(1)
        self.driver.execute_script("window.scrollBy(0,800)")
        time.sleep(1)
        self.enter_text(Locators.BULK_PUNCHDATE, "14-12-2024")
        time.sleep(1)
        self.enter_text(Locators.BULK_PUNCHTIME, "15:00")
        time.sleep(1)

        self.click(Locators.BULK_ASSIGN)
        time.sleep(1)
        self.click(Locators.BULK_SUBMIT)
        time.sleep(1)
        self.logger.info("Bulk Punches Added successfully")
        # # self.dropdown_click(Locators.BULK_EMP, 3)
        # # time.sleep(2)
        # # self.dropdown_click(Locators.BULK_EMP, 4)
        # # time.sleep(2)
        # # self.dropdown_click(Locators.BULK_EMP, 5)
        # # time.sleep(2)
        # self.enter_text(Locators.BULK_TIME, "09.00")
        # time.sleep(2)
        # self.enter_text(Locators.BULK_DATE, "12-04-2028")
        # time.sleep(2)
        # self.click(Locators.BULK_SAVE)
        # time.sleep(2)
        # self.click(Locators.BULK_ATT)
        # time.sleep(2)
        # self.enter_text(Locators.BULK_TIME_2, "17.00")
        # time.sleep(2)
        # self.click(Locators.BULK_SAVE)
        # time.sleep(2)

    def individual(self):
        self.click(Locators.INDIVIDUAL_TAB)
        time.sleep(3)
        self.dropdown_click(Locators.INDIVIDUAL_EMP, 1)
        time.sleep(1)
        self.enter_text(Locators.INDIVIDUAL_DATE, "12-04-2024")
        time.sleep(1)
        self.enter_text(Locators.INDIVIDUAL_PUNCHTIME, "16:00")
        time.sleep(1)
        self.click(Locators.INDIVIDUAL_SAVE)
        time.sleep(5)
        self.click(Locators.INDIVIDUAL_EDIT)
        time.sleep(3)
        self.enter_text(Locators.INDIVIDUAL_EDIT_PUNCH, "17:00")
        time.sleep(1)
        self.click(Locators.INDIVIDUAL_EDIT_SAVE)
        time.sleep(1)
        self.logger.info("Individual Punch is  Updated successfully")
        self.click(Locators.INDIVIDUAL_DELETE)
        time.sleep(1)
        self.logger.info("Individual Punch is  Deleted successfully")
        

    def attendance(self):
        self.attendance_tab()
        self.bulk_add()
        self.individual()
        self.all()
        self.single_punch()
        self.outofshift_punch()
        self.minimum_shift_mins()
        self.odd_punch()

