[pytest]
markers =
    manage_data: mark test for managing data
    document_creation: mark test for document creation
    manage_document: mark test for managing documents
    login: mark test for login functionality
    homepage: mark test for homepage
    forms: mark test for forms
    checklistreport: mark test for checklist reports
    formfilledreports: mark test for form-filled reports
    defaultreport: mark test for default report
    agingreport: mark test for aging report
    assign: mark test for assigning
    actiontracker: mark test for action tracker
    establishrealation: mark test for establishing relationship
    calendar: mark test for calendar
    actionstage: mark test for action stage
    assettype: mark test for asset types
    group: mark test for groups
    compcode: mark test for company code
    datatable: mark test for datatable
